services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: inventario
      POSTGRES_USER: inventario
      POSTGRES_PASSWORD: inventario
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  inventario:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inventario
      SPRING_DATASOURCE_USERNAME: inventario
      SPRING_DATASOURCE_PASSWORD: inventario
    ports:
      - "8082:8082"
    depends_on:
      - postgres

volumes:
  pgdata: {}
