server:
  port: 8082
  address: 0.0.0.0

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/inventario}
    username: ${SPRING_DATASOURCE_USERNAME:inventario}
    password: ${SPRING_DATASOURCE_PASSWORD:inventario}
  jpa:
    hibernate:
      ddl-auto: update  # en prod: cambiar a validate y usar migraciones (Flyway/Liquibase)
    properties:
      hibernate:
        jdbc.time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: "*"

# springdoc swagger-ui:
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
